### ISSUE TITLE
Cannot install dedaemon from NPM: dedaemon@0.2.5 postinstall fails

### ISSUE THREAD

**Issue by hgoldstein** [mortie/dedaemon#2]
# Problem
I am unable to install `dedaemon` from NPM; here is my output:
```
~ $ sudo npm install -g dedaemon
[sudo] password for hunter: 
/usr/local/bin/dedaemon -> /usr/local/lib/node_modules/dedaemon/dedaemon.js

> dedaemon@0.2.5 postinstall /usr/local/lib/node_modules/dedaemon
> make -C udev

make: Entering directory '/usr/local/lib/node_modules/dedaemon/udev'
cc -o udev-monitor -g -ludev src/main.c src/json.c
/usr/bin/ld: cannot open output file udev-monitor: Permission denied
collect2: error: ld returned 1 exit status
Makefile:7: recipe for target 'udev-monitor' failed
make: *** [udev-monitor] Error 1
make: Leaving directory '/usr/local/lib/node_modules/dedaemon/udev'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dedaemon@0.2.5 postinstall: `make -C udev`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the dedaemon@0.2.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hunter/.npm/_logs/2017-06-22T13_24_28_499Z-debug.log
```
A couple notes:
- This output is from a Ubuntu 16.04 machine
- I also tried from an Arch Linux machine and got the same result
- If I clone this repo I can run `postinstall` with no issues

**Comment by mortie** [comment]
Thanks for reporting this. It seems to be an issue only on npm 5; it appears they're no longer running postinstall scripts as root even though npm was run as root. I hadn't updated from 4.6.1 yet, and thus hadn't noticed. I'll get to work on fixing it immediately, but as a temporary fix, you can run `sudo npm install -g --unsafe-perm dedaemon`.

**Comment by mortie** [comment]
This seems to be an issue which affects all projects which have `postinstall` scripts which need write access. I created an issue in npm's issue tracker: https://github.com/npm/npm/issues/17391

For now, I'll just update the documentation to include `--unsafe-perm`.

**Comment by mortie** [comment]
Closing the issue since there's nothing to do unless NPM fixes it, and the `--unsafe-perm` solution works.
